### ISSUE TITLE
Can not import excel file after update "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by Rudeka** [UweKeim/ZetaResourceEditor#22]
After update there is an error when I want to import earlier exported and modified excel file, error message:

System.NullReferenceException

-----------------

Object reference not set to an instance of an object.

-----------------

at ZetaResourceEditor.RuntimeBusinessLogic.ExportImportExcel.CoreExcel2.CoreExcelImporter.createDataTable(Worksheet ws) in c:\P\ZetaResourceEditor\Source\RuntimeBusinessLogic\ExportImportExcel\CoreExcel2\CoreExcelImporter.cs:line 41
   at ZetaResourceEditor.RuntimeBusinessLogic.ExportImportExcel.CoreExcel2.CoreExcelImporter.ImportExcelFromFile(String filePath) in c:\P\ZetaResourceEditor\Source\RuntimeBusinessLogic\ExportImportExcel\CoreExcel2\CoreExcelImporter.cs:line 17
   at ZetaResourceEditor.RuntimeBusinessLogic.ExportImportExcel.Import.ExcelImportController.DetectFileGroupsFromExcelFile(Project project, String filePath) in c:\P\ZetaResourceEditor\Source\RuntimeBusinessLogic\ExportImportExcel\Import\ExcelImportController.cs:line 53
   at ZetaResourceEditor.UI.ExportImportExcel.ExcelImportWizardForm.parseFileGroups() in c:\P\ZetaResourceEditor\Source\Main\UI\ExportImportExcel\ExcelImportWizardForm.cs:line 368
   at ZetaResourceEditor.UI.ExportImportExcel.ExcelImportWizardForm.sourceFileTextEdit_EditValueChanged(Object sender, EventArgs e) in c:\P\ZetaResourceEditor\Source\Main\UI\ExportImportExcel\ExcelImportWizardForm.cs:line 464
   at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChangedCore(EventArgs e)
   at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChanged(EventArgs e)
   at DevExpress.XtraEditors.BaseEdit.RaiseEditValueChanged()
   at DevExpress.XtraEditors.BaseEdit.OnEditValueChanged()
   at DevExpress.XtraEditors.TextEdit.OnEditValueChanged()
   at DevExpress.XtraEditors.MemoEdit.OnEditValueChanged()
   at ExtendedControlsLibrary.General.ExtendedManagedCueMemoEdit.OnEditValueChanged() in c:\P\ZetaResourceEditor\Source-Skinning\ExtendedControlsLibrary\General\ExtendedManagedCueMemoEdit.cs:line 71
   at DevExpress.XtraEditors.BaseEdit.OnEditValueChanging(ChangingEventArgs e)
   at DevExpress.XtraEditors.TextEdit.OnEditValueChanging(ChangingEventArgs e)
   at DevExpress.XtraEditors.BaseEdit.set_EditValue(Object value)
   at ExtendedControlsLibrary.General.ExtendedManagedCueMemoEdit.set_Text(String value) in c:\P\ZetaResourceEditor\Source-Skinning\ExtendedControlsLibrary\General\ExtendedManagedCueMemoEdit.cs:line 42
   at ZetaResourceEditor.UI.ExportImportExcel.ExcelImportWizardForm.restoreState(IPersistentPairStorage storage) in c:\P\ZetaResourceEditor\Source\Main\UI\ExportImportExcel\ExcelImportWizardForm.cs:line 195
   at ZetaResourceEditor.UI.ExportImportExcel.ExcelImportWizardForm.FillItemToControls() in c:\P\ZetaResourceEditor\Source\Main\UI\ExportImportExcel\ExcelImportWizardForm.cs:line 168
   at ZetaResourceEditor.UI.ExportImportExcel.ExcelImportWizardForm.ImportWizard_Load(Object sender, EventArgs e) in c:\P\ZetaResourceEditor\Source\Main\UI\ExportImportExcel\ExcelImportWizardForm.cs:line 139
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at ExtendedControlsLibrary.Skinning.CustomForm.MyXtraForm.OnLoad(EventArgs e) in c:\P\ZetaResourceEditor\Source-Skinning\ExtendedControlsLibrary\Skinning\CustomForm\MyXtraForm.cs:line 105
   at ExtendedControlsLibrary.General.Base.DevExpressXtraFormBase.OnLoad(EventArgs e) in c:\P\ZetaResourceEditor\Source-Skinning\ExtendedControlsLibrary\General\Base\DevExpressXtraFormBase.cs:line 138
   at ZetaResourceEditor.UI.Helper.Base.FormBase.OnLoad(EventArgs e) in c:\P\ZetaResourceEditor\Source\Main\UI\Helper\Base\FormBase.cs:line 55
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

NullReferenceException
{
	Message="Object reference not set to an instance of an object.",
	Data=
	[
	]
,
	InnerException=null,
	TargetSite=RuntimeMethodInfo: createDataTable,
	StackTrace="   at ZetaResourceEditor.RuntimeBusinessLogic.ExportImportExcel.CoreExcel2.CoreExcelImporter.createDataTable(Worksheet ws) in c:\\P\\ZetaResourceEditor\\Source\\RuntimeBusinessLogic\\ExportImportExcel\\CoreExcel2\\CoreExcelImporter.cs:line 41\\r\\n   at ZetaResourceEditor.RuntimeBusinessLogic.ExportImportExcel.CoreExcel2.CoreExcelImporter.ImportExcelFromFile(String filePath) in c:\\P\\ZetaResourceEditor\\Source\\RuntimeBusinessLogic\\ExportImportExcel\\CoreExcel2\\CoreExcelImporter.cs:line 17\\r\\n   at ZetaResourceEditor.RuntimeBusinessLogic.ExportImportExcel.Import.ExcelImportController.DetectFileGroupsFromExcelFile(Project project, String filePath) in c:\\P\\ZetaResourceEditor\\Source\\RuntimeBusinessLogic\\ExportImportExcel\\Import\\ExcelImportController.cs:line 53\\r\\n   at ZetaResourceEditor.UI.ExportImportExcel.ExcelImportWizardForm.parseFileGroups() in c:\\P\\ZetaResourceEditor\\Source\\Main\\UI\\ExportImportExcel\\ExcelImportWizardForm.cs:line 368\\r\\n   at ZetaResourceEditor.UI.ExportImportExcel.ExcelImportWizardForm.sourceFileTextEdit_EditValueChanged(Object sender, EventArgs e) in c:\\P\\ZetaResourceEditor\\Source\\Main\\UI\\ExportImportExcel\\ExcelImportWizardForm.cs:line 464\\r\\n   at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChangedCore(EventArgs e)\\r\\n   at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChanged(EventArgs e)\\r\\n   at DevExpress.XtraEditors.BaseEdit.RaiseEditValueChanged()\\r\\n   at DevExpress.XtraEditors.BaseEdit.OnEditValueChanged()\\r\\n   at DevExpress.XtraEditors.TextEdit.OnEditValueChanged()\\r\\n   at DevExpress.XtraEditors.MemoEdit.OnEditValueChanged()\\r\\n   at ExtendedControlsLibrary.General.ExtendedManagedCueMemoEdit.OnEditValueChanged() in c:\\P\\ZetaResourceEditor\\Source-Skinning\\ExtendedControlsLibrary\\General\\ExtendedManagedCueMemoEdit.cs:line 71\\r\\n   at DevExpress.XtraEditors.BaseEdit.OnEditValueChanging(ChangingEventArgs e)\\r\\n   at DevExpress.XtraEditors.TextEdit.OnEditValueChanging(ChangingEventArgs e)\\r\\n   at DevExpress.XtraEditors.BaseEdit.set_EditValue(Object value)\\r\\n   at ExtendedControlsLibrary.General.ExtendedManagedCueMemoEdit.set_Text(String value) in c:\\P\\ZetaResourceEditor\\Source-Skinning\\ExtendedControlsLibrary\\General\\ExtendedManagedCueMemoEdit.cs:line 42\\r\\n   at ZetaResourceEditor.UI.ExportImportExcel.ExcelImportWizardForm.restoreState(IPersistentPairStorage storage) in c:\\P\\ZetaResourceEditor\\Source\\Main\\UI\\ExportImportExcel\\ExcelImportWizardForm.cs:line 195\\r\\n   at ZetaResourceEditor.UI.ExportImportExcel.ExcelImportWizardForm.FillItemToControls() in c:\\P\\ZetaResourceEditor\\Source\\Main\\UI\\ExportImportExcel\\ExcelImportWizardForm.cs:line 168\\r\\n   at ZetaResourceEditor.UI.ExportImportExcel.ExcelImportWizardForm.ImportWizard_Load(Object sender, EventArgs e) in c:\\P\\ZetaResourceEditor\\Source\\Main\\UI\\ExportImportExcel\\ExcelImportWizardForm.cs:line 139\\r\\n   at System.EventHandler.Invoke(Object sender, EventArgs e)\\r\\n   at System.Windows.Forms.Form.OnLoad(EventArgs e)\\r\\n   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)\\r\\n   at ExtendedControlsLibrary.Skinning.CustomForm.MyXtraForm.OnLoad(EventArgs e) in c:\\P\\ZetaResourceEditor\\Source-Skinning\\ExtendedControlsLibrary\\Skinning\\CustomForm\\MyXtraForm.cs:line 105\\r\\n   at ExtendedControlsLibrary.General.Base.DevExpressXtraFormBase.OnLoad(EventArgs e) in c:\\P\\ZetaResourceEditor\\Source-Skinning\\ExtendedControlsLibrary\\General\\Base\\DevExpressXtraFormBase.cs:line 138\\r\\n   at ZetaResourceEditor.UI.Helper.Base.FormBase.OnLoad(EventArgs e) in c:\\P\\ZetaResourceEditor\\Source\\Main\\UI\\Helper\\Base\\FormBase.cs:line 55\\r\\n   at System.Windows.Forms.Form.OnCreateControl()\\r\\n   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)\\r\\n   at System.Windows.Forms.Control.CreateControl()\\r\\n   at System.Windows.Forms.Control.WmShowWindow(Message& m)\\r\\n   at System.Windows.Forms.Control.WndProc(Message& m)\\r\\n   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)\\r\\n   at System.Windows.Forms.Form.WmShowWindow(Message& m)\\r\\n   at System.Windows.Forms.Form.WndProc(Message& m)\\r\\n   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)\\r\\n   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)\\r\\n   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)\\r\\n   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)",
	HelpLink=null,
	Source="ZetaResourceEditor.RuntimeBusinessLogic",
	HResult=-2147467261
}

**Comment by UweKeim** [comment]
Please provide the Excel file to me.

**Comment by Rudeka** [comment]
I think the reason was, that excel file was exported by previouse version of Zeta. If I export excel file with a new version and modify it, then it is imported with no errors.
I fixed my issue this way. 
But for testing porposes attaching problem excel file
[ZetaTestFile.xlsx](https://github.com/UweKeim/ZetaResourceEditor/files/813854/ZetaTestFile.xlsx)

**Comment by UweKeim** [comment]
Thanks, I fixed my code with the help of your test Excel file.

**Comment by Rudeka** [comment]
Always happy to contribute ;)
