### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by arcuri** [UweKeim/ZetaResourceEditor#30]
I tried to traslate a text ... but the application throw an exeption.

Can you help me?

System.Net.WebException

-----------------

The remote server returned an error: (403) Forbidden.

-----------------

at System.Net.HttpWebRequest.GetResponse()
   at ZetaResourceEditor.RuntimeBusinessLogic.Translation.Google.GoogleRestfulTranslationEngine.makeRestCallPost(String appID, String url, ICollection`1 parameters) in c:\P\ZetaResourceEditor\Source\RuntimeBusinessLogic\Translation\Google\GoogleRestfulTranslationEngine.cs:line 100
   at ZetaResourceEditor.RuntimeBusinessLogic.Translation.Google.GoogleRestfulTranslationEngine.Translate(String appID, String appID2, String text, String sourceLanguageCode, String destinationLanguageCode, String[] wordsToProtect, String[] wordsToRemove) in c:\P\ZetaResourceEditor\Source\RuntimeBusinessLogic\Translation\Google\GoogleRestfulTranslationEngine.cs:line 258
   at ZetaResourceEditor.UI.Translation.QuickTranslationForm.buttonTranslate_Click(Object sender, EventArgs e) in c:\P\ZetaResourceEditor\Source\Main\UI\Translation\QuickTranslationForm.cs:line 301

WebException
{
	Status=ProtocolError,
	Response=HttpWebResponse
	{
		IsMutuallyAuthenticated=False,
		Cookies=CookieCollection
		{
			IsReadOnly=True,
			Count=0,
			IsSynchronized=False,

		},
		Headers=WebHeaderCollection
		{
			Count=11,
			Keys=KeysCollection
			{
				Count=11
			},
			AllKeys=String[]
			{
				Length=11,
				LongLength=11,
				Rank=1,
,
				IsReadOnly=False,
				IsFixedSize=True,
				IsSynchronized=False

				"Vary",
				"X-XSS-Protection",
				"X-Frame-Options",
				"X-Content-Type-Options",
				"Alt-Svc",
				"Transfer-Encoding",
				"Accept-Ranges",
				"Cache-Control",
				"Content-Type",
				"Date",
				"Server"
			},
		},
		SupportsHeaders=True,
		ContentLength=-1,
		ContentEncoding="",
		ContentType="application/json; charset=UTF-8",
		CharacterSet="UTF-8",
		Server="ESF",
		LastModified=04.12.17 08:32:02,
		StatusCode=Forbidden,
		StatusDescription="Forbidden",
		ProtocolVersion=Version
		{
			Major=1,
			Minor=1,
			Build=-1,
			Revision=-1,
			MajorRevision=-1,
			MinorRevision=-1
		},
		ResponseUri=Uri
		{
			AbsolutePath="/language/translate/v2",
			AbsoluteUri="https://www.googleapis.com/language/translate/v2?",
			LocalPath="/language/translate/v2",
			Authority="www.googleapis.com",
			HostNameType=Dns,
			IsDefaultPort=True,
			IsFile=False,
			IsLoopback=False,
			PathAndQuery="/language/translate/v2?",
			Segments=String[]
			{
				Length=4,
				LongLength=4,
				Rank=1,
,
				IsReadOnly=False,
				IsFixedSize=True,
				IsSynchronized=False

				"/",
				"language/",
				"translate/",
				"v2"
			},
			IsUnc=False,
			Host="www.googleapis.com",
			Port=443,
			Query="?",
			Fragment="",
			Scheme="https",
			OriginalString="https://www.googleapis.com/language/translate/v2?",
			DnsSafeHost="www.googleapis.com",
			IdnHost="www.googleapis.com",
			IsAbsoluteUri=True,
			UserEscaped=False,
			UserInfo=""
		},
		Method="POST",
		IsFromCache=False
	},
	Message="The remote server returned an error: (403) Forbidden.",
	Data=
	[
	]
,
	InnerException=null,
	TargetSite=RuntimeMethodInfo: GetResponse,
	StackTrace="   at System.Net.HttpWebRequest.GetResponse()\\r\\n   at ZetaResourceEditor.RuntimeBusinessLogic.Translation.Google.GoogleRestfulTranslationEngine.makeRestCallPost(String appID, String url, ICollection`1 parameters) in c:\\P\\ZetaResourceEditor\\Source\\RuntimeBusinessLogic\\Translation\\Google\\GoogleRestfulTranslationEngine.cs:line 100\\r\\n   at ZetaResourceEditor.RuntimeBusinessLogic.Translation.Google.GoogleRestfulTranslationEngine.Translate(String appID, String appID2, String text, String sourceLanguageCode, String destinationLanguageCode, String[] wordsToProtect, String[] wordsToRemove) in c:\\P\\ZetaResourceEditor\\Source\\RuntimeBusinessLogic\\Translation\\Google\\GoogleRestfulTranslationEngine.cs:line 258\\r\\n   at ZetaResourceEditor.UI.Translation.QuickTranslationForm.buttonTranslate_Click(Object sender, EventArgs e) in c:\\P\\ZetaResourceEditor\\Source\\Main\\UI\\Translation\\QuickTranslationForm.cs:line 301",
	HelpLink=null,
	Source="System",
	HResult=-2146233079
}

**Comment by UweKeim** [comment]
Could be wrong credentials entered.
