### ISSUE TITLE
Error creating new files for language.

### ISSUE THREAD

**Issue by KentJohnsonW** [UweKeim/ZetaResourceEditor#53]
I'm trying to use this tool to send resource files to partners to be translated, so I cannot send the entire Visual Studio solution. So I pulled the resource files for each project into a separate directory with each project in it's own folder, then I created a new project, and added files from that directory (manually or automatically doesn't matter). The outcome is the same though, if I only use the files from one project.

When I click "create new file for language" I get the error:

System.ArgumentException

-----------------

The path is empty. (Parameter 'path')

-----------------

at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo..ctor(String fileName)
   at ZetaResourceEditor.UI.FileGroups.CreateNewFileForm.updateIncludeFileInCsprojControls() in c:\P\zeta-resource-editor\Source\Main\UI\FileGroups\CreateNewFileForm.cs:line 85
   at ZetaResourceEditor.UI.FileGroups.CreateNewFileForm.UpdateUI() in c:\P\zeta-resource-editor\Source\Main\UI\FileGroups\CreateNewFileForm.cs:line 103
   at ZetaResourceEditor.UI.FileGroups.CreateNewFileForm.prefixTextBox_EditValueChanged(Object sender, EventArgs e) in c:\P\zeta-resource-editor\Source\Main\UI\FileGroups\CreateNewFileForm.cs:line 356
   at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChangedCore(EventArgs e)
   at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChanged(EventArgs e)
   at DevExpress.XtraEditors.BaseEdit.RaiseEditValueChanged()
   at DevExpress.XtraEditors.BaseEdit.OnEditValueChanged()
   at DevExpress.XtraEditors.TextEdit.OnEditValueChanged()
   at ZetaResourceEditor.ExtendedControlsLibrary.General.ExtendedManagedCueTextEdit.OnEditValueChanged() in c:\P\zeta-resource-editor\Source\ExtendedControlsLibrary\General\ExtendedManagedCueTextEdit.cs:line 70
   at DevExpress.XtraEditors.BaseEdit.OnEditValueChanging(ChangingEventArgs e)
   at DevExpress.XtraEditors.TextEdit.OnEditValueChanging(ChangingEventArgs e)
   at DevExpress.XtraEditors.BaseEdit.set_EditValue(Object value)
   at DevExpress.XtraEditors.BaseEdit.set_Text(String value)
   at DevExpress.XtraEditors.TextEdit.SetBaseText(String text)
   at DevExpress.XtraEditors.TextEdit.TextEditWorkingStrategy.set_Text(String value)
   at DevExpress.XtraEditors.TextEdit.set_Text(String value)
   at ZetaResourceEditor.ExtendedControlsLibrary.General.ExtendedManagedCueTextEdit.set_Text(String value) in c:\P\zeta-resource-editor\Source\ExtendedControlsLibrary\General\ExtendedManagedCueTextEdit.cs:line 41
   at ZetaResourceEditor.UI.FileGroups.CreateNewFileForm.FillItemToControls() in c:\P\zeta-resource-editor\Source\Main\UI\FileGroups\CreateNewFileForm.cs:line 137
   at ZetaResourceEditor.UI.FileGroups.CreateNewFileForm.CreateNewFileForm_Load(Object sender, EventArgs e) in c:\P\zeta-resource-editor\Source\Main\UI\FileGroups\CreateNewFileForm.cs:line 244
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)
   at ZetaResourceEditor.ExtendedControlsLibrary.Skinning.CustomForm.MyXtraForm.OnLoad(EventArgs e) in c:\P\zeta-resource-editor\Source\ExtendedControlsLibrary\Skinning\CustomForm\MyXtraForm.cs:line 61
   at ZetaResourceEditor.ExtendedControlsLibrary.General.Base.DevExpressXtraFormBase.OnLoad(EventArgs e) in c:\P\zeta-resource-editor\Source\ExtendedControlsLibrary\General\Base\DevExpressXtraFormBase.cs:line 133
   at ZetaResourceEditor.UI.Helper.Base.FormBase.OnLoad(EventArgs e) in c:\P\zeta-resource-editor\Source\Main\UI\Helper\Base\FormBase.cs:line 45
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.DForm.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

ArgumentException
{
	Message="The path is empty. (Parameter \\'path\\')",
	ParamName="path",
	TargetSite=RuntimeMethodInfo: GetFullPath,
	Data=
	[
	]
,
	InnerException=null,
	HelpLink=null,
	Source="System.Private.CoreLib",
	HResult=-2147024809,
	StackTrace="   at System.IO.Path.GetFullPath(String path)\\r\\n   at System.IO.FileInfo..ctor(String fileName)\\r\\n   at ZetaResourceEditor.UI.FileGroups.CreateNewFileForm.updateIncludeFileInCsprojControls() in c:\\P\\zeta-resource-editor\\Source\\Main\\UI\\FileGroups\\CreateNewFileForm.cs:line 85\\r\\n   at ZetaResourceEditor.UI.FileGroups.CreateNewFileForm.UpdateUI() in c:\\P\\zeta-resource-editor\\Source\\Main\\UI\\FileGroups\\CreateNewFileForm.cs:line 103\\r\\n   at ZetaResourceEditor.UI.FileGroups.CreateNewFileForm.prefixTextBox_EditValueChanged(Object sender, EventArgs e) in c:\\P\\zeta-resource-editor\\Source\\Main\\UI\\FileGroups\\CreateNewFileForm.cs:line 356\\r\\n   at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChangedCore(EventArgs e)\\r\\n   at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseEditValueChanged(EventArgs e)\\r\\n   at DevExpress.XtraEditors.BaseEdit.RaiseEditValueChanged()\\r\\n   at DevExpress.XtraEditors.BaseEdit.OnEditValueChanged()\\r\\n   at DevExpress.XtraEditors.TextEdit.OnEditValueChanged()\\r\\n   at ZetaResourceEditor.ExtendedControlsLibrary.General.ExtendedManagedCueTextEdit.OnEditValueChanged() in c:\\P\\zeta-resource-editor\\Source\\ExtendedControlsLibrary\\General\\ExtendedManagedCueTextEdit.cs:line 70\\r\\n   at DevExpress.XtraEditors.BaseEdit.OnEditValueChanging(ChangingEventArgs e)\\r\\n   at DevExpress.XtraEditors.TextEdit.OnEditValueChanging(ChangingEventArgs e)\\r\\n   at DevExpress.XtraEditors.BaseEdit.set_EditValue(Object value)\\r\\n   at DevExpress.XtraEditors.BaseEdit.set_Text(String value)\\r\\n   at DevExpress.XtraEditors.TextEdit.SetBaseText(String text)\\r\\n   at DevExpress.XtraEditors.TextEdit.TextEditWorkingStrategy.set_Text(String value)\\r\\n   at DevExpress.XtraEditors.TextEdit.set_Text(String value)\\r\\n   at ZetaResourceEditor.ExtendedControlsLibrary.General.ExtendedManagedCueTextEdit.set_Text(String value) in c:\\P\\zeta-resource-editor\\Source\\ExtendedControlsLibrary\\General\\ExtendedManagedCueTextEdit.cs:line 41\\r\\n   at ZetaResourceEditor.UI.FileGroups.CreateNewFileForm.FillItemToControls() in c:\\P\\zeta-resource-editor\\Source\\Main\\UI\\FileGroups\\CreateNewFileForm.cs:line 137\\r\\n   at ZetaResourceEditor.UI.FileGroups.CreateNewFileForm.CreateNewFileForm_Load(Object sender, EventArgs e) in c:\\P\\zeta-resource-editor\\Source\\Main\\UI\\FileGroups\\CreateNewFileForm.cs:line 244\\r\\n   at System.Windows.Forms.Form.OnLoad(EventArgs e)\\r\\n   at DevExpress.XtraEditors.XtraForm.OnLoad(EventArgs e)\\r\\n   at ZetaResourceEditor.ExtendedControlsLibrary.Skinning.CustomForm.MyXtraForm.OnLoad(EventArgs e) in c:\\P\\zeta-resource-editor\\Source\\ExtendedControlsLibrary\\Skinning\\CustomForm\\MyXtraForm.cs:line 61\\r\\n   at ZetaResourceEditor.ExtendedControlsLibrary.General.Base.DevExpressXtraFormBase.OnLoad(EventArgs e) in c:\\P\\zeta-resource-editor\\Source\\ExtendedControlsLibrary\\General\\Base\\DevExpressXtraFormBase.cs:line 133\\r\\n   at ZetaResourceEditor.UI.Helper.Base.FormBase.OnLoad(EventArgs e) in c:\\P\\zeta-resource-editor\\Source\\Main\\UI\\Helper\\Base\\FormBase.cs:line 45\\r\\n   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)\\r\\n   at System.Windows.Forms.Control.CreateControl()\\r\\n   at System.Windows.Forms.Control.WmShowWindow(Message& m)\\r\\n   at System.Windows.Forms.Control.WndProc(Message& m)\\r\\n   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)\\r\\n   at System.Windows.Forms.Form.WmShowWindow(Message& m)\\r\\n   at System.Windows.Forms.Form.WndProc(Message& m)\\r\\n   at DevExpress.XtraEditors.DForm.WndProc(Message& m)\\r\\n   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)\\r\\n   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)\\r\\n   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)"
}

**Comment by UweKeim** [comment]
I've tried to reproduce this issue on my side, unfortunately without success.

Could you please assemble me a small set of RESX files together with a ZREPROJ file so that I can debug this constellation and fix the issue?

**Comment by KentJohnsonW** [comment]
[Sample Resources.zip](https://github.com/UweKeim/ZetaResourceEditor/files/10768203/Sample.Resources.zip)
Here is a sample of the resource files I'm using. I just create a new project, and "automatically add multiple file groups to project" select this folder, and then when I open it for editing and click "create new file for language" the error pops up.

**Comment by UweKeim** [comment]
Thanks, this helped.

I've just released an updated versions, should be notified soon when starting Zeta Resource Editor the next time.
